# Generated by Django 2.1.1 on 2019-01-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
