# Generated by Django 2.1.1 on 2019-01-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_update_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type_of_profile',
            field=models.CharField(choices=[('TE', 'Teacher'), ('SU', 'Student')], default='SU', max_length=2),
        ),
    ]
